// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'dev-web-api-key',
    appId: 'dev-web-app-id',
    messagingSenderId: 'dev-sender-id',
    projectId: 'dev-project-id',
    authDomain: 'dev-project.firebaseapp.com',
    storageBucket: 'dev-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dev-android-api-key',
    appId: 'dev-android-app-id',
    messagingSenderId: 'dev-sender-id',
    projectId: 'dev-project-id',
    storageBucket: 'dev-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dev-ios-api-key',
    appId: 'dev-ios-app-id',
    messagingSenderId: 'dev-sender-id',
    projectId: 'dev-project-id',
    storageBucket: 'dev-project.appspot.com',
    iosClientId: 'dev-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'dev-macos-api-key',
    appId: 'dev-macos-app-id',
    messagingSenderId: 'dev-sender-id',
    projectId: 'dev-project-id',
    storageBucket: 'dev-project.appspot.com',
    iosClientId: 'dev-macos-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'dev-windows-api-key',
    appId: 'dev-windows-app-id',
    messagingSenderId: 'dev-sender-id',
    projectId: 'dev-project-id',
    authDomain: 'dev-project.firebaseapp.com',
    storageBucket: 'dev-project.appspot.com',
  );
}
